application: simple-life
version: 1
runtime: python27
threadsafe: no
api_version: 1

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /partials
  static_dir: static/partials/

- url: /.*
  script: main.application
